# Generated by Django 4.2 on 2023-08-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('idAirline', models.BigAutoField(db_column='idAirline', primary_key=True, serialize=False)),
                ('nombreAirline', models.CharField(db_column='nombreAirline', max_length=255, unique=True, verbose_name='Nombre de la Aerolinea')),
            ],
        ),
        migrations.CreateModel(
            name='FlightManifest',
            fields=[
                ('idFlightManifest', models.BigAutoField(db_column='idFlightManifest', primary_key=True, serialize=False)),
                ('OperatorCode', models.CharField(db_column='OperatorCode', max_length=255, verbose_name='Codigo de Operador')),
                ('Date', models.DateField(blank=True, null=True, verbose_name='Fecha de guardado')),
                ('Matricula', models.CharField(db_column='Matricula', max_length=255, verbose_name='Matricula de Aeronave')),
                ('numeroVuelo', models.CharField(db_column='numeroVuelo', max_length=255, verbose_name='Numero de Vuelo')),
                ('tipoAeroNave', models.CharField(db_column='tipoAeroNave', max_length=255, verbose_name='Tipo de AeroNave')),
                ('llegadas', models.TimeField(blank=True, null=True, verbose_name='Fecha de Llegada')),
                ('salidas', models.TimeField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('destino', models.CharField(db_column='destino', max_length=255, verbose_name='Destino')),
                ('codigoATO', models.CharField(db_column='codigoATO', max_length=255, verbose_name='codigo ATO')),
                ('nombreATO', models.CharField(db_column='nombreATO', max_length=255, verbose_name='nombre ATO')),
                ('totalPax', models.IntegerField(blank=True, max_length=255, null=True)),
                ('paxExen', models.IntegerField(max_length=255)),
                ('inf', models.IntegerField(max_length=255)),
                ('collect', models.IntegerField(max_length=255)),
                ('terceraEdad', models.IntegerField(max_length=255)),
                ('paxCargados', models.IntegerField(max_length=255)),
                ('comentarios', models.CharField(db_column='comentarios', max_length=255, verbose_name='comentarios')),
                ('idAirline', models.ForeignKey(db_column='nombreAirline', on_delete=django.db.models.deletion.DO_NOTHING, to='Manifest.airlines', verbose_name='Nombre de la Aerolinea')),
            ],
        ),
    ]
