# Generated by Django 4.2 on 2023-08-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('idAirline', models.BigAutoField(db_column='idAirline', primary_key=True, serialize=False)),
                ('nombreAirline', models.CharField(db_column='nombreAirline', max_length=255, unique=True, verbose_name='Nombre de la Aerolinea')),
                ('logoAirline', models.ImageField(blank=True, null=True, upload_to='airlinesChck/')),
            ],
        ),
        migrations.CreateModel(
            name='FlightDestination',
            fields=[
                ('idFlightDestination', models.BigAutoField(db_column='idFlightDestination', primary_key=True, serialize=False)),
                ('nombreFlightDestination', models.CharField(db_column='nombreFlightDestination', max_length=255, unique=True, verbose_name='Destino del Vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='StatusFlight',
            fields=[
                ('idStatusFlight', models.BigAutoField(db_column='idStatusFlight', primary_key=True, serialize=False)),
                ('nombreStatusFlight', models.CharField(db_column='nombreStatusFlight', max_length=255, unique=True, verbose_name='Estado del Vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('idGate', models.BigAutoField(db_column='idGate', primary_key=True, serialize=False)),
                ('GateNumber', models.CharField(max_length=100, unique=True)),
                ('FlightNumber', models.CharField(max_length=100)),
                ('StatusDisplay', models.BooleanField(default=False)),
                ('idAirline', models.ForeignKey(db_column='nombreAirline', on_delete=django.db.models.deletion.DO_NOTHING, to='counter.airline', verbose_name='Aerolinea')),
                ('idFlightDestination', models.ForeignKey(db_column='nombreFlightDestination', on_delete=django.db.models.deletion.DO_NOTHING, to='counter.flightdestination', verbose_name='Destino del Vuelo')),
                ('idStatusFlight', models.ForeignKey(db_column='nombreStatusFlight', on_delete=django.db.models.deletion.DO_NOTHING, to='counter.statusflight', verbose_name='Estado del Vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('idCheckIn', models.BigAutoField(db_column='idCheckIn', primary_key=True, serialize=False)),
                ('CheckinNumber', models.CharField(max_length=50, unique=True)),
                ('FlightNumber', models.CharField(max_length=100)),
                ('StatusDisplay', models.BooleanField(default=False)),
                ('idAirline', models.ForeignKey(db_column='nombreAirline', on_delete=django.db.models.deletion.DO_NOTHING, to='counter.airline', verbose_name='Aerolinea')),
                ('idFlightDestination', models.ForeignKey(db_column='nombreFlightDestination', on_delete=django.db.models.deletion.DO_NOTHING, to='counter.flightdestination', verbose_name='Destino del Vuelo')),
                ('idStatusFlight', models.ForeignKey(db_column='nombreStatusFlight', on_delete=django.db.models.deletion.DO_NOTHING, to='counter.statusflight', verbose_name='Estado del Vuelo')),
            ],
        ),
    ]
